### ISSUE TITLE
Is there a way to enable the microphone?

### ISSUE THREAD

**Issue by edisan27** [jessebofill/DeckWebBrowser#1]
I really love this browser.
I want to play while I voice chatting with Discord, but microphone seems disabled/blocked by the browser when I try to use.

**Comment by jessebofill** [comment]
It may be possible to do. I'll have to look into it, but I won't be able to right away. Maybe in the next week or so.

**Comment by jessebofill** [comment]
Unfortunately, it looks like access to the microphone is disabled by the browser internally so it is not possible. Sorry.

**Comment by jessebofill** [comment]
@edisan27 Writing to let you know I have implemented a custom solution. The feature is now available in 1.4.0
