### ISSUE TITLE
After OS update and DeckyLoader updated to latest version it does not worked

### ISSUE THREAD

**Issue by dtantono** [jessebofill/DeckWebBrowser#12]
Hi
I updated the plugin to 1.3.0 and 1.3.1 and OS update and deckyloader. the plugin does not worked anymore
https://store.steampowered.com/news/app/1675200/view/4124805233776242150

**Comment by Garywoo** [comment]
Can you describe the issue or error message you're seeing? Screenshots would be useful.

**Comment by jessebofill** [comment]
Yeah I know the latest steam update has broken something. I haven’t had a chance to look into it yet. But I will when I can.

**Comment by jessebofill** [comment]
The fix will be in the next update, which should make it to the store soon.
