### ISSUE TITLE
FR: more favorites options

### ISSUE THREAD

**Issue by deluxghost** [jessebofill/DeckWebBrowser#13]
I found it's annoying to modify favorites when I made some mistakes. I must delete the favorite, re-type its url, go to the website, add favorite, and type its title again, while it's not easy to type on steam deck

It will be easier to manage favorites with following options:

- edit the favorite's
   - title
   - url
   - location (i.e. move to another folder)
- edit the name of folders
- order sites/folders

**Comment by jessebofill** [comment]
I appreciate the suggestion and understand how it would be useful. But I don't think it's worth the time/ effort that it would take to implement it. Sorry.
