### ISSUE TITLE
TypeError after latest update

### ISSUE THREAD

**Issue by NoelleTGS** [jessebofill/DeckWebBrowser#14]
The latest update gives me a TypeError when opening the plugin from the plugin menu, and the browser does not show in the Steam menu.
![20240320162823_1](https://github.com/jessebofill/DeckWebBrowser/assets/44215890/162abebd-e5d9-4c96-96d9-081072d27299)

**Comment by Fofer** [comment]
Same here. Thanks for reporting.

**Comment by Slvrtnge** [comment]
Also same thanks for posting!

**Comment by jessebofill** [comment]
This update needs the latest decky prerelease. If you switch to that it will work.
