### ISSUE TITLE
Mobile user agent setting

### ISSUE THREAD

**Issue by Wibbbs** [jessebofill/DeckWebBrowser#17]
A bit of a feature request here, unless there is a way to do this already that I am missing. I would love to see a way to request the mobile version of pages.

Not sure what user agent the browser is sending now but maybe a way could be added to spoof a mobile user agent.

**Comment by jessebofill** [comment]
I don’t have too much time to look into this right now. The plugin uses built in steam components which sets the user agent itself and as far as I can remember it cannot be changed. I’m pretty sure I’ve tried to do it before. But when I have a chance next time I’m working on it, I’ll look into it again to see if it’s possible.

**Comment by fennectech** [comment]
Welp    Came to request this.    Bummer.  Would be nice to get google sign in working.
