### ISSUE TITLE
Plugin not working on Latest SteamOS stable build

### ISSUE THREAD

**Issue by DraconicNEO** [jessebofill/DeckWebBrowser#22]
Trying to us the latest one in the store (1.3.1) and it gives an error. I'm currently running the lastest stable SteamOS version which is 3.6.19 and build 20241021.100.
The plugin gives an exception when trying to load.

**Comment by jessebofill** [comment]
The next version fixes it which is already submitted to the store. We just have to wait for it to go through the testing process.
