### ISSUE TITLE
TypeError on 3.6.20

### ISSUE THREAD

**Issue by Khromfair** [jessebofill/DeckWebBrowser#23]
With the new SteamOS update the TypeError has returned.
![IMG_4990](https://github.com/user-attachments/assets/da0559ed-a662-4e8a-9f5c-9e18cd755a89)

This time on 3.6.20

**Comment by jessebofill** [comment]
The fix is already submitted to the store. I’m just waiting for it to go through the testing process.

**Comment by jessebofill** [comment]
> @jessebofill hi, do you have aby ETA? It's been 2 weeks already

Yeah it’s just waiting for the decky reviewers

**Comment by mPogrzebski** [comment]
@jessebofill I reckon you should submit it again. It got lost or something. Do you know who can push it through? I'll tag them

**Comment by jessebofill** [comment]
> @jessebofill I reckon you should submit it again. It got lost or something. Do you know who can push it through? I'll tag them

I already requested a couple times in the discord. Sometimes they just get busy and it takes a bit for them to get around to it.

**Comment by mPogrzebski** [comment]
Ah nice, thanks 👍

**Comment by jessebofill** [comment]
It’s now in testing store. If anyone could help test it would be appreciated

**Comment by Ninpop0** [comment]
> It’s now in testing store. If anyone could help test it would be appreciated

I used it like I use it normally and nothing to Say it works perfectly hope it will be soon in stable channel. Thanks @jessebofill

**Comment by mPogrzebski** [comment]
Works like a charm! Thanks

**Comment by jessebofill** [comment]
good to hear. if either of you guys would be willing to do a testing report, that would be helpful to get it to stable quicker. https://wiki.deckbrew.xyz/user-guide/testing

**Comment by jessebofill** [comment]
This fix is finally in the store! Be aware that there is a new issue on latest steam beta client though.
