### ISSUE TITLE
Web Browser Borked on new SteamOS update

### ISSUE THREAD

**Issue by thanone2** [jessebofill/DeckWebBrowser#24]
![image](https://github.com/user-attachments/assets/8fa49fed-53c4-49ad-95ab-b587f88c9984)
here's a screenshot of the error it's throwing at me

**Comment by jessebofill** [comment]
Are you running the testing store version?

**Comment by DraconicNEO** [comment]
How is it that you sent in the update over 2 months ago and it's still stuck in the testing phase. Decky's Store really needs to step up their Game. This should've been released from Testing long ago, it's a browser plugin FFS
 
(I'm not mad at you, I'm mad at them for sitting on their ass for over 2 months)

**Comment by jessebofill** [comment]
> How is it that you sent in the update over 2 months ago and it's still stuck in the testing phase. Decky's Store really needs to step up their Game. This should've been released from Testing long ago, it's a browser plugin FFS
> 
> (I'm not mad at you, I'm mad at them for sitting on their ass for over 2 months)

I understand the frustration but please understand that these projects are maintained by volunteers in there spare time and often times get busy with other priorities. So having to wait is just how it goes.

**Comment by DraconicNEO** [comment]
> > How is it that you sent in the update over 2 months ago and it's still stuck in the testing phase. Decky's Store really needs to step up their Game. This should've been released from Testing long ago, it's a browser plugin FFS
> > (I'm not mad at you, I'm mad at them for sitting on their ass for over 2 months)
> 
> I understand the frustration but please understand that these projects are maintained by volunteers in there spare time and often times get busy with other priorities. So having to wait is just how it goes.

The problem is that Decky store is centralized. If they stop giving shits and let plugins go they hurt it for everyone. So I'm less inclined to give them a pass than I would be if the stores were just like repositories on Linux where you can start or add a different one that doesn't have the waiting restrictions.
