### ISSUE TITLE
can't access integrated URL bar

### ISSUE THREAD

**Issue by ask-compu** [jessebofill/DeckWebBrowser#4]
it can't be tapped or navigated to via the controls

**Comment by jessebofill** [comment]
Press B to highlight to highlight the tab bar. Then go up from there.

**Comment by ask-compu** [comment]
ah, might wanna add that to the section of the readme about the url bar

**Comment by jessebofill** [comment]
Oh yeah will do. I thought I had mentioned that somewhere but guess not.

**Comment by chronokz** [comment]
If you see a lock icon 🔒  in the address bar and you can't change the address, then make sure the Developer Mode is enabled.
![image](https://github.com/jessebofill/DeckWebBrowser/assets/1516523/79a2c592-88cf-4583-bf22-82824cd09d43)

**Comment by jessebofill** [comment]
> If you see a lock icon 🔒 in the address bar and you can't change the address, then make sure the Developer Mode is enabled.
> ![image](https://user-images.githubusercontent.com/1516523/255223578-79a2c592-88cf-4583-bf22-82824cd09d43.png)

I’m not sure what you mean by this. This shouldn’t have any effect on this plugin.

**Comment by chronokz** [comment]
@jessebofill I had this problem while I had the original Steam OS. 
A few moments ago I reinstalled the OS and this action is no longer required for new installs.
Just leave the message if someone like I was could have the similiar issue.
