### ISSUE TITLE
Any options for cleaning caches？

### ISSUE THREAD

**Issue by ilworkcn** [jessebofill/DeckWebBrowser#6]
hello，maintainer。

Does this plugin generate cached files of web pages？and if so, is there a cleanup option?

**Comment by jessebofill** [comment]
This uses cef which is what runs the whole steam deck ui. I’m not sure if it caches pages. I’ll have to look into it and get back to you.

**Comment by jessebofill** [comment]
sorry it's taken so long, but if you go into deck settings->internet, all the way at the bottom there is the option to "Delete Web Browser Data". This should delete cached files, cookies and history.

**Comment by ilworkcn** [comment]
> sorry it's taken so long, but if you go into deck settings->internet, all the way at the bottom there is the option to "Delete Web Browser Data". This should delete cached files, cookies and history.

Thank you very much🫶

**Comment by jessebofill** [comment]
You’re welcome.
