### ISSUE TITLE
More search engine options

### ISSUE THREAD

**Issue by Kreachers** [jessebofill/DeckWebBrowser#8]
Some more search options would be awesome. I personally like using duckduckgo but I know there's others that exist that some folks may want.

**Comment by jessebofill** [comment]
i'm thinking i may just allow user to use any search engine they want by providing the url with correct query format

**Comment by Kreachers** [comment]
Yeah, I was thinking that would be best. I just don't know how many people know how to set that up if they are just prompted by a text field.

**Comment by jessebofill** [comment]
> Yeah, I was thinking that would be best. I just don't know how many people know how to set that up if they are just prompted by a text field.

yeah, i also had that thought, but not sure what best solution would be.

**Comment by jessebofill** [comment]
This feature has been implemented in 1.3.0 which just released on decky store a few days ago. You can use any custom search url as long as you format it correctly. The dialog box when entering custom url describes how it should be formatted.
