### ISSUE TITLE
Option to display PC version steam web pages?

### ISSUE THREAD

**Issue by deluxghost** [jessebofill/DeckWebBrowser#9]
when I open any steam pages in the browser, they are shown in steam deck layout. Is it possible to add an context menu option to show the standard version? (similar to "desktop website" option in mobile browsers)

**Comment by jessebofill** [comment]
> when I open any steam pages in the browser, they are shown in steam deck layout. Is it possible to add an context menu option to show the standard version? (similar to "desktop website" option in mobile browsers)

I’m not sure if it’s possible. I’ll have to look into it.

**Comment by jessebofill** [comment]
Unfortunately there is not a simple way to do this that I know of.
